 spring.security.user.name=user
 spring.security.user.password=pass

# ??????? H2 console (?? ???????)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ????????? JPA ??? ???????? UserEntity (???? ??????????? ??-??????)
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:file:./data/demo;MODE=PostgreSQL;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=true
spring.sql.init.mode=always
